code_quality:
  image: docker:latest
  allow_failure: true
  script:
    - docker pull codeclimate/codeclimate
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        codeclimate /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
  tags:
    - quality